name: Publish PowerShell Build

on:
  push:
    branch: [develop-workflow]

jobs:
  publish-to-gallery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        shell: pwsh
        run: |
          ./build.ps1 "3.2.0" -archive -Path /tmp/samplemodule

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-artifacts
          path: /tmp/samplemodule
 
